[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-gilear"
description = "Parser for the Gilear language"
version = "0.0.0"
keywords = ["incremental", "parsing", "tree-sitter", "gilear"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Wen Kokke", email = "wenkokke@users.noreply.github.com" }]
requires-python = ">=3.9"
license.text = "NONE"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/wenkokke/gilear"

[project.optional-dependencies]
core = ["tree-sitter~=0.22"]

[tool.cibuildwheel]
build = "cp39-*"
build-frontend = "build"
