name: "Setup cabal-docspec"
description: "Install a specific cabal-docspec version"
inputs:
  cabal-docspec-version:
    required: true
    description: "Version of cabal-docspec"
runs:
  using: composite
  steps:
    - name: 💾 Restore cache
      uses: actions/cache/restore@v4
      if: ${{ !env.ACT }}
      id: cache-cabal-docspec
      with:
        path: "${{ github.workspace }}/.cabal-docspec/bin"
        key: ${{ runner.os }}-cabal-docspec-${{ inputs.cabal-docspec-version }}

    - name: 🛠️ Install cabal-docspec
      if: ${{ runner.os == 'Linux' }}
      run: |
        mkdir -p "${{ github.workspace }}/.cabal-docspec/bin"
        curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-${{ inputs.cabal-docspec-version }}/cabal-docspec-${{ inputs.cabal-docspec-version }}-x86_64-linux.xz > "${{ runner.temp }}/cabal-docspec.xz"
        echo '48bf3b7fd2f7f0caa6162afee57a755be8523e7f467b694900eb420f5f9a7b76  ${{ runner.temp }}/cabal-docspec.xz' | sha256sum -c -
        xz -d < "${{ runner.temp }}/cabal-docspec.xz" > "${{ github.workspace }}/.cabal-docspec/bin/cabal-docspec"
        chmod a+x "${{ github.workspace }}/.cabal-docspec/bin/cabal-docspec"
      shell: sh

    - name: 🛠️ Add cabal-docspec to PATH
      run: echo "${{ github.workspace }}/.cabal-docspec/bin" >> "$GITHUB_PATH"
      shell: sh

    - name: 💾 Save cache
      uses: actions/cache/save@v4
      if: ${{ !env.ACT && steps.cache-cabal-docspec.outputs.cache-hit != 'true' }}
      with:
        path: "${{ github.workspace }}/.cabal-docspec/bin"
        key: ${{ steps.cache-cabal-docspec.outputs.cache-primary-key }}
