{-# LANGUAGE RankNTypes #-}

module TreeSitter (
  module TreeSitter.Internal,
) where

import TreeSitter.Internal (
  CancellationFlag (..),
  CancellationFlagRef,
  CaptureIndex (..),
  CaptureName (..),
  FieldId,
  FieldName (..),
  GrammarType (..),
  Input,
  InputEdit (..),
  InputEncoding (..),
  Language,
  LogType,
  Logger,
  LookaheadIterator,
  Microsecond (..),
  Node,
  NodeId (..),
  Parser,
  PatternIndex (..),
  Point (..),
  Quantifier,
  Query,
  QueryCapture,
  QueryCursor,
  QueryError (..),
  QueryErrorType (..),
  QueryMatch,
  QueryPredicateStep,
  QueryPredicateStepType,
  Range (..),
  Symbol,
  SymbolType (..),
  TREE_SITTER_LANGUAGE_VERSION,
  TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION,
  Tree,
  TreeCursor,
  TreeCursorId (..),
  getCancellationFlag,
  languageCopy,
  languageFieldCount,
  languageFieldIdForName,
  languageFieldNameForId,
  languageNextState,
  languageStateCount,
  languageSymbolCount,
  languageSymbolForGrammarType,
  languageSymbolName,
  languageSymbolType,
  languageVersion,
  loggerNew,
  nodeChild,
  nodeChildByFieldId,
  nodeChildByFieldName,
  nodeChildCount,
  nodeChildWithDescendant,
  nodeDescendantCount,
  nodeDescendantForByteRange,
  nodeDescendantForPointRange,
  nodeEdit,
  nodeEndByte,
  nodeEndPoint,
  nodeEq,
  nodeFieldNameForChild,
  nodeFieldNameForChildAsString,
  nodeFieldNameForNamedChild,
  nodeFieldNameForNamedChildAsString,
  nodeFirstChildForByte,
  nodeFirstNamedChildForByte,
  nodeGrammarSymbol,
  nodeGrammarType,
  nodeGrammarTypeAsString,
  nodeHasChanges,
  nodeHasError,
  nodeId,
  nodeIsError,
  nodeIsExtra,
  nodeIsMissing,
  nodeIsNamed,
  nodeIsNull,
  nodeLanguage,
  nodeNamedChild,
  nodeNamedChildCount,
  nodeNamedDescendantForByteRange,
  nodeNamedDescendantForPointRange,
  nodeNextNamedSibling,
  nodeNextParseState,
  nodeNextSibling,
  nodeParent,
  nodeParseState,
  nodePrevNamedSibling,
  nodePrevSibling,
  nodeStartByte,
  nodeStartPoint,
  nodeSymbol,
  nodeType,
  nodeTypeAsString,
  parserCancellationFlag,
  parserHasLogger,
  parserIncludedRanges,
  parserLogger,
  parserNew,
  parserParseByteString,
  parserParseByteStringWithEncoding,
  parserParseString,
  parserPrintDotGraphs,
  parserRemoveLogger,
  parserReset,
  parserSetCancellationFlag,
  parserSetIncludedRanges,
  parserSetLanguage,
  parserSetLogger,
  parserSetTimeoutMicros,
  parserTimeoutMicros,
  putCancellationFlag,
  queryCaptureCount,
  queryCaptureNameForIndex,
  queryCaptureQuantifierForIndex,
  queryCursorDidExceedMatchLimit,
  queryCursorExec,
  queryCursorMatchLimit,
  queryCursorNew,
  queryCursorNextCapture,
  queryCursorNextMatch,
  queryCursorRemoveMatch,
  queryCursorSetByteRange,
  queryCursorSetMatchLimit,
  queryCursorSetMaxStartDepth,
  queryCursorSetPointRange,
  queryCursorSetTimeoutMicros,
  queryCursorTimeoutMicros,
  queryDisableCapture,
  queryDisablePattern,
  queryEndByteForPattern,
  queryIsPatternGuaranteedAtStep,
  queryIsPatternNonLocal,
  queryIsPatternRooted,
  queryNew,
  queryPatternCount,
  queryPredicatesForPattern,
  queryStartByteForPattern,
  queryStringCount,
  queryStringValueForIndex,
  showNode,
  showNodeAsString,
  treeCopy,
  treeCursorCopy,
  treeCursorCurrentDepth,
  treeCursorCurrentDescendantIndex,
  treeCursorCurrentFieldId,
  treeCursorCurrentFieldName,
  treeCursorCurrentNode,
  treeCursorGotoDescendant,
  treeCursorGotoFirstChild,
  treeCursorGotoFirstChildForByte,
  treeCursorGotoFirstChildForPoint,
  treeCursorGotoLastChild,
  treeCursorGotoNextSibling,
  treeCursorGotoParent,
  treeCursorGotoPreviousSibling,
  treeCursorNew,
  treeCursorReset,
  treeCursorResetTo,
  treeEdit,
  treeGetChangedRanges,
  treeIncludedRanges,
  treeLanguage,
  treePrintDotGraph,
  treeRootNode,
  treeRootNodeWithOffset,
  unsafeLanguageDelete,
  unsafeLoggerDelete,
  unsafeParserDelete,
  unsafeParserDeleteLogger,
  unsafeQueryCursorDelete,
  unsafeQueryDelete,
  unsafeToLanguage,
  unsafeTreeCursorDelete,
  unsafeTreeDelete,
  withParser,
 )
