#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_COLON_EQ = 1,
  sym_skip = 2,
  anon_sym_SEMI = 3,
  anon_sym_if = 4,
  anon_sym_then = 5,
  anon_sym_else = 6,
  anon_sym_while = 7,
  anon_sym_do = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  sym_true = 11,
  sym_false = 12,
  anon_sym_not = 13,
  anon_sym_and = 14,
  anon_sym_or = 15,
  sym_lt = 16,
  sym_le = 17,
  sym_eq = 18,
  sym_gt = 19,
  sym_ge = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  sym_number = 27,
  sym_variable = 28,
  sym_source_file = 29,
  sym_statements = 30,
  aux_sym__statements = 31,
  sym_statement = 32,
  sym__statement = 33,
  sym_assignment = 34,
  sym_sequence = 35,
  sym_if_then_else = 36,
  sym_while_do = 37,
  sym__bracketed_statements = 38,
  sym__predicate = 39,
  sym_negation = 40,
  sym_conjunction = 41,
  sym_disjunction = 42,
  sym_comparison = 43,
  sym__comparison_operator = 44,
  sym__parenthesized_predicate = 45,
  sym_expression = 46,
  sym__expression = 47,
  sym_addition = 48,
  sym_subtraction = 49,
  sym_multiplication = 50,
  sym_division = 51,
  sym__parenthesized_expression = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_EQ] = ":=",
  [sym_skip] = "skip",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_true] = "true",
  [sym_false] = "false",
  [anon_sym_not] = "not",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [sym_lt] = "lt",
  [sym_le] = "le",
  [sym_eq] = "eq",
  [sym_gt] = "gt",
  [sym_ge] = "ge",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_number] = "number",
  [sym_variable] = "variable",
  [sym_source_file] = "source_file",
  [sym_statements] = "statements",
  [aux_sym__statements] = "_statements",
  [sym_statement] = "statement",
  [sym__statement] = "_statement",
  [sym_assignment] = "assignment",
  [sym_sequence] = "sequence",
  [sym_if_then_else] = "if_then_else",
  [sym_while_do] = "while_do",
  [sym__bracketed_statements] = "_bracketed_statements",
  [sym__predicate] = "_predicate",
  [sym_negation] = "negation",
  [sym_conjunction] = "conjunction",
  [sym_disjunction] = "disjunction",
  [sym_comparison] = "comparison",
  [sym__comparison_operator] = "_comparison_operator",
  [sym__parenthesized_predicate] = "_parenthesized_predicate",
  [sym_expression] = "expression",
  [sym__expression] = "_expression",
  [sym_addition] = "addition",
  [sym_subtraction] = "subtraction",
  [sym_multiplication] = "multiplication",
  [sym_division] = "division",
  [sym__parenthesized_expression] = "_parenthesized_expression",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_skip] = sym_skip,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [sym_lt] = sym_lt,
  [sym_le] = sym_le,
  [sym_eq] = sym_eq,
  [sym_gt] = sym_gt,
  [sym_ge] = sym_ge,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_number] = sym_number,
  [sym_variable] = sym_variable,
  [sym_source_file] = sym_source_file,
  [sym_statements] = sym_statements,
  [aux_sym__statements] = aux_sym__statements,
  [sym_statement] = sym_statement,
  [sym__statement] = sym__statement,
  [sym_assignment] = sym_assignment,
  [sym_sequence] = sym_sequence,
  [sym_if_then_else] = sym_if_then_else,
  [sym_while_do] = sym_while_do,
  [sym__bracketed_statements] = sym__bracketed_statements,
  [sym__predicate] = sym__predicate,
  [sym_negation] = sym_negation,
  [sym_conjunction] = sym_conjunction,
  [sym_disjunction] = sym_disjunction,
  [sym_comparison] = sym_comparison,
  [sym__comparison_operator] = sym__comparison_operator,
  [sym__parenthesized_predicate] = sym__parenthesized_predicate,
  [sym_expression] = sym_expression,
  [sym__expression] = sym__expression,
  [sym_addition] = sym_addition,
  [sym_subtraction] = sym_subtraction,
  [sym_multiplication] = sym_multiplication,
  [sym_division] = sym_division,
  [sym__parenthesized_expression] = sym__parenthesized_expression,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_skip] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statements] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__statements] = {
    .visible = false,
    .named = false,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_if_then_else] = {
    .visible = true,
    .named = true,
  },
  [sym_while_do] = {
    .visible = true,
    .named = true,
  },
  [sym__bracketed_statements] = {
    .visible = false,
    .named = true,
  },
  [sym__predicate] = {
    .visible = false,
    .named = true,
  },
  [sym_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_disjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym__comparison_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__parenthesized_predicate] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_subtraction] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplication] = {
    .visible = true,
    .named = true,
  },
  [sym_division] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesized_expression] = {
    .visible = false,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_right = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 8,
  [14] = 9,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 26,
  [29] = 23,
  [30] = 2,
  [31] = 10,
  [32] = 11,
  [33] = 5,
  [34] = 12,
  [35] = 27,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 41,
  [47] = 43,
  [48] = 48,
  [49] = 39,
  [50] = 44,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 21,
  [58] = 58,
  [59] = 59,
  [60] = 58,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 67,
  [68] = 65,
  [69] = 51,
  [70] = 70,
  [71] = 56,
  [72] = 54,
  [73] = 53,
  [74] = 70,
  [75] = 52,
  [76] = 76,
  [77] = 77,
  [78] = 77,
  [79] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '(', 58,
        ')', 59,
        '*', 62,
        '+', 60,
        '-', 61,
        '/', 63,
        ':', 3,
        ';', 35,
        '<', 53,
        '=', 55,
        '>', 56,
        'a', 20,
        'd', 22,
        'e', 17,
        'f', 4,
        'i', 11,
        'n', 23,
        'o', 25,
        's', 16,
        't', 12,
        'w', 13,
        '{', 43,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(58);
      if (lookahead == 'f') ADVANCE(65);
      if (lookahead == 'n') ADVANCE(76);
      if (lookahead == 't') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        ')', 59,
        '*', 62,
        '+', 60,
        '-', 61,
        '/', 63,
        ';', 35,
        '<', 53,
        '=', 55,
        '>', 56,
        'i', 69,
        's', 73,
        'w', 70,
        '{', 43,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_skip);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_skip);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_if);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_while);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_true);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_false);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_not);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_le);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ge);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'a') ADVANCE(75);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(41);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(48);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'f') ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'h') ADVANCE(72);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'i') ADVANCE(77);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'i') ADVANCE(74);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'k') ADVANCE(71);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(66);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'l') ADVANCE(79);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'o') ADVANCE(80);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'p') ADVANCE(34);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'r') ADVANCE(81);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 's') ADVANCE(68);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 't') ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'u') ADVANCE(67);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_variable);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 30},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 30},
  [27] = {.lex_state = 30},
  [28] = {.lex_state = 30},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 30},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 30},
  [52] = {.lex_state = 30},
  [53] = {.lex_state = 30},
  [54] = {.lex_state = 30},
  [55] = {.lex_state = 30},
  [56] = {.lex_state = 30},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [sym_skip] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_le] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_ge] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym_statements] = STATE(76),
    [aux_sym__statements] = STATE(18),
    [sym_statement] = STATE(18),
    [sym__statement] = STATE(55),
    [sym_assignment] = STATE(55),
    [sym_sequence] = STATE(55),
    [sym_if_then_else] = STATE(55),
    [sym_while_do] = STATE(55),
    [sym__bracketed_statements] = STATE(55),
    [sym_skip] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_while] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_variable] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(15), 6,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_variable,
    ACTIONS(13), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [23] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(17), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(63), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [56] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      sym_variable,
    ACTIONS(27), 2,
      sym_true,
      sym_false,
    STATE(25), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(67), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [89] = 2,
    ACTIONS(35), 6,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_variable,
    ACTIONS(33), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [112] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(37), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(62), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [145] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(39), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(61), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [178] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(41), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(65), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [211] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(43), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(64), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [244] = 4,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(47), 6,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_variable,
    ACTIONS(45), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [271] = 4,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(55), 6,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_variable,
    ACTIONS(53), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [298] = 2,
    ACTIONS(59), 6,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_lt,
      sym_gt,
      sym_variable,
    ACTIONS(57), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_le,
      sym_eq,
      sym_ge,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [321] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(61), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(68), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [354] = 7,
    ACTIONS(19), 1,
      anon_sym_not,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      sym_variable,
    ACTIONS(63), 2,
      sym_true,
      sym_false,
    STATE(38), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
    STATE(66), 6,
      sym__predicate,
      sym_negation,
      sym_conjunction,
      sym_disjunction,
      sym_comparison,
      sym__parenthesized_predicate,
  [387] = 8,
    ACTIONS(67), 1,
      sym_skip,
    ACTIONS(70), 1,
      anon_sym_if,
    ACTIONS(73), 1,
      anon_sym_while,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      sym_variable,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(15), 2,
      aux_sym__statements,
      sym_statement,
    STATE(55), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [419] = 8,
    ACTIONS(3), 1,
      sym_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      aux_sym__statements,
      sym_statement,
    STATE(55), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [450] = 8,
    ACTIONS(3), 1,
      sym_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      aux_sym__statements,
      sym_statement,
    STATE(55), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [481] = 8,
    ACTIONS(3), 1,
      sym_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    STATE(15), 2,
      aux_sym__statements,
      sym_statement,
    STATE(55), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [512] = 7,
    ACTIONS(3), 1,
      sym_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    STATE(16), 2,
      aux_sym__statements,
      sym_statement,
    STATE(55), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [540] = 7,
    ACTIONS(3), 1,
      sym_skip,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    STATE(17), 2,
      aux_sym__statements,
      sym_statement,
    STATE(55), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [568] = 6,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_PLUS,
    ACTIONS(94), 1,
      anon_sym_DASH,
    ACTIONS(88), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(90), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [593] = 6,
    ACTIONS(96), 1,
      sym_skip,
    ACTIONS(98), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_while,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      sym_variable,
    STATE(69), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [617] = 6,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(106), 1,
      sym_skip,
    STATE(56), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [641] = 6,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(108), 1,
      sym_skip,
    STATE(51), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [665] = 8,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_PLUS,
    ACTIONS(94), 1,
      anon_sym_DASH,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym__comparison_operator,
    ACTIONS(110), 2,
      sym_lt,
      sym_gt,
    ACTIONS(112), 3,
      sym_le,
      sym_eq,
      sym_ge,
  [693] = 6,
    ACTIONS(98), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_while,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      sym_variable,
    ACTIONS(116), 1,
      sym_skip,
    STATE(70), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [717] = 6,
    ACTIONS(5), 1,
      anon_sym_if,
    ACTIONS(7), 1,
      anon_sym_while,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_variable,
    ACTIONS(118), 1,
      sym_skip,
    STATE(54), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [741] = 6,
    ACTIONS(98), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_while,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      sym_variable,
    ACTIONS(120), 1,
      sym_skip,
    STATE(74), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [765] = 6,
    ACTIONS(98), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_while,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      sym_variable,
    ACTIONS(122), 1,
      sym_skip,
    STATE(71), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [789] = 1,
    ACTIONS(13), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [803] = 3,
    ACTIONS(124), 1,
      anon_sym_STAR,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    ACTIONS(45), 9,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [821] = 3,
    ACTIONS(124), 1,
      anon_sym_STAR,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    ACTIONS(53), 9,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [839] = 1,
    ACTIONS(33), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [853] = 1,
    ACTIONS(57), 11,
      anon_sym_SEMI,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [867] = 6,
    ACTIONS(98), 1,
      anon_sym_if,
    ACTIONS(100), 1,
      anon_sym_while,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      sym_variable,
    ACTIONS(128), 1,
      sym_skip,
    STATE(72), 6,
      sym__statement,
      sym_assignment,
      sym_sequence,
      sym_if_then_else,
      sym_while_do,
      sym__bracketed_statements,
  [891] = 4,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_expression,
    ACTIONS(132), 2,
      sym_number,
      sym_variable,
    STATE(21), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [910] = 4,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    STATE(75), 1,
      sym_expression,
    ACTIONS(136), 2,
      sym_number,
      sym_variable,
    STATE(57), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [929] = 7,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_PLUS,
    ACTIONS(94), 1,
      anon_sym_DASH,
    STATE(48), 1,
      sym__comparison_operator,
    ACTIONS(110), 2,
      sym_lt,
      sym_gt,
    ACTIONS(112), 3,
      sym_le,
      sym_eq,
      sym_ge,
  [954] = 3,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 2,
      sym_number,
      sym_variable,
    STATE(12), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [970] = 5,
    ACTIONS(124), 1,
      anon_sym_STAR,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    ACTIONS(142), 1,
      anon_sym_PLUS,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(140), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [990] = 3,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 2,
      sym_number,
      sym_variable,
    STATE(58), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1006] = 3,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(148), 2,
      sym_number,
      sym_variable,
    STATE(5), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1022] = 3,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    ACTIONS(150), 2,
      sym_number,
      sym_variable,
    STATE(31), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1038] = 3,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 2,
      sym_number,
      sym_variable,
    STATE(32), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1054] = 3,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 2,
      sym_number,
      sym_variable,
    STATE(33), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1070] = 3,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 2,
      sym_number,
      sym_variable,
    STATE(60), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1086] = 3,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(158), 2,
      sym_number,
      sym_variable,
    STATE(10), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1102] = 3,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    ACTIONS(160), 2,
      sym_number,
      sym_variable,
    STATE(40), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1118] = 3,
    ACTIONS(134), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 2,
      sym_number,
      sym_variable,
    STATE(34), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1134] = 3,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 2,
      sym_number,
      sym_variable,
    STATE(11), 6,
      sym__expression,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym__parenthesized_expression,
  [1150] = 3,
    ACTIONS(170), 1,
      anon_sym_SEMI,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(168), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [1165] = 2,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(174), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [1178] = 2,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(178), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [1191] = 3,
    ACTIONS(170), 1,
      anon_sym_SEMI,
    ACTIONS(180), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(182), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [1206] = 3,
    ACTIONS(170), 1,
      anon_sym_SEMI,
    ACTIONS(184), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(186), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [1221] = 3,
    ACTIONS(170), 1,
      anon_sym_SEMI,
    ACTIONS(188), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(190), 4,
      sym_skip,
      anon_sym_if,
      anon_sym_while,
      sym_variable,
  [1236] = 5,
    ACTIONS(124), 1,
      anon_sym_STAR,
    ACTIONS(126), 1,
      anon_sym_SLASH,
    ACTIONS(142), 1,
      anon_sym_PLUS,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1253] = 5,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_PLUS,
    ACTIONS(94), 1,
      anon_sym_DASH,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
  [1269] = 1,
    ACTIONS(192), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1277] = 5,
    ACTIONS(49), 1,
      anon_sym_STAR,
    ACTIONS(51), 1,
      anon_sym_SLASH,
    ACTIONS(92), 1,
      anon_sym_PLUS,
    ACTIONS(94), 1,
      anon_sym_DASH,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
  [1293] = 2,
    ACTIONS(198), 1,
      anon_sym_and,
    ACTIONS(196), 4,
      anon_sym_then,
      anon_sym_do,
      anon_sym_or,
      anon_sym_RPAREN,
  [1303] = 1,
    ACTIONS(200), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1311] = 1,
    ACTIONS(202), 5,
      anon_sym_then,
      anon_sym_do,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
  [1319] = 3,
    ACTIONS(198), 1,
      anon_sym_and,
    ACTIONS(204), 1,
      anon_sym_do,
    ACTIONS(206), 1,
      anon_sym_or,
  [1329] = 3,
    ACTIONS(198), 1,
      anon_sym_and,
    ACTIONS(206), 1,
      anon_sym_or,
    ACTIONS(208), 1,
      anon_sym_then,
  [1339] = 3,
    ACTIONS(198), 1,
      anon_sym_and,
    ACTIONS(206), 1,
      anon_sym_or,
    ACTIONS(210), 1,
      anon_sym_do,
  [1349] = 3,
    ACTIONS(198), 1,
      anon_sym_and,
    ACTIONS(206), 1,
      anon_sym_or,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
  [1359] = 3,
    ACTIONS(198), 1,
      anon_sym_and,
    ACTIONS(206), 1,
      anon_sym_or,
    ACTIONS(214), 1,
      anon_sym_then,
  [1369] = 2,
    ACTIONS(166), 1,
      anon_sym_else,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [1376] = 2,
    ACTIONS(216), 1,
      anon_sym_SEMI,
    ACTIONS(218), 1,
      anon_sym_else,
  [1383] = 2,
    ACTIONS(188), 1,
      anon_sym_else,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [1390] = 2,
    ACTIONS(180), 1,
      anon_sym_else,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [1397] = 1,
    ACTIONS(176), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1402] = 2,
    ACTIONS(216), 1,
      anon_sym_SEMI,
    ACTIONS(220), 1,
      anon_sym_else,
  [1409] = 1,
    ACTIONS(172), 2,
      anon_sym_SEMI,
      anon_sym_else,
  [1414] = 1,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
  [1418] = 1,
    ACTIONS(224), 1,
      anon_sym_COLON_EQ,
  [1422] = 1,
    ACTIONS(226), 1,
      anon_sym_COLON_EQ,
  [1426] = 1,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 89,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 178,
  [SMALL_STATE(9)] = 211,
  [SMALL_STATE(10)] = 244,
  [SMALL_STATE(11)] = 271,
  [SMALL_STATE(12)] = 298,
  [SMALL_STATE(13)] = 321,
  [SMALL_STATE(14)] = 354,
  [SMALL_STATE(15)] = 387,
  [SMALL_STATE(16)] = 419,
  [SMALL_STATE(17)] = 450,
  [SMALL_STATE(18)] = 481,
  [SMALL_STATE(19)] = 512,
  [SMALL_STATE(20)] = 540,
  [SMALL_STATE(21)] = 568,
  [SMALL_STATE(22)] = 593,
  [SMALL_STATE(23)] = 617,
  [SMALL_STATE(24)] = 641,
  [SMALL_STATE(25)] = 665,
  [SMALL_STATE(26)] = 693,
  [SMALL_STATE(27)] = 717,
  [SMALL_STATE(28)] = 741,
  [SMALL_STATE(29)] = 765,
  [SMALL_STATE(30)] = 789,
  [SMALL_STATE(31)] = 803,
  [SMALL_STATE(32)] = 821,
  [SMALL_STATE(33)] = 839,
  [SMALL_STATE(34)] = 853,
  [SMALL_STATE(35)] = 867,
  [SMALL_STATE(36)] = 891,
  [SMALL_STATE(37)] = 910,
  [SMALL_STATE(38)] = 929,
  [SMALL_STATE(39)] = 954,
  [SMALL_STATE(40)] = 970,
  [SMALL_STATE(41)] = 990,
  [SMALL_STATE(42)] = 1006,
  [SMALL_STATE(43)] = 1022,
  [SMALL_STATE(44)] = 1038,
  [SMALL_STATE(45)] = 1054,
  [SMALL_STATE(46)] = 1070,
  [SMALL_STATE(47)] = 1086,
  [SMALL_STATE(48)] = 1102,
  [SMALL_STATE(49)] = 1118,
  [SMALL_STATE(50)] = 1134,
  [SMALL_STATE(51)] = 1150,
  [SMALL_STATE(52)] = 1165,
  [SMALL_STATE(53)] = 1178,
  [SMALL_STATE(54)] = 1191,
  [SMALL_STATE(55)] = 1206,
  [SMALL_STATE(56)] = 1221,
  [SMALL_STATE(57)] = 1236,
  [SMALL_STATE(58)] = 1253,
  [SMALL_STATE(59)] = 1269,
  [SMALL_STATE(60)] = 1277,
  [SMALL_STATE(61)] = 1293,
  [SMALL_STATE(62)] = 1303,
  [SMALL_STATE(63)] = 1311,
  [SMALL_STATE(64)] = 1319,
  [SMALL_STATE(65)] = 1329,
  [SMALL_STATE(66)] = 1339,
  [SMALL_STATE(67)] = 1349,
  [SMALL_STATE(68)] = 1359,
  [SMALL_STATE(69)] = 1369,
  [SMALL_STATE(70)] = 1376,
  [SMALL_STATE(71)] = 1383,
  [SMALL_STATE(72)] = 1390,
  [SMALL_STATE(73)] = 1397,
  [SMALL_STATE(74)] = 1402,
  [SMALL_STATE(75)] = 1409,
  [SMALL_STATE(76)] = 1414,
  [SMALL_STATE(77)] = 1418,
  [SMALL_STATE(78)] = 1422,
  [SMALL_STATE(79)] = 1426,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_expression, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesized_expression, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication, 3, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiplication, 3, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 3, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 3, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtraction, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subtraction, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 3, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 3, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements, 2, 0, 0), SHIFT_REPEAT(55),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements, 2, 0, 0), SHIFT_REPEAT(8),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements, 2, 0, 0), SHIFT_REPEAT(9),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements, 2, 0, 0), SHIFT_REPEAT(20),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statements, 2, 0, 0), SHIFT_REPEAT(77),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statements, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 3, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bracketed_statements, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bracketed_statements, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_then_else, 6, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_then_else, 6, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_do, 4, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_do, 4, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_predicate, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_disjunction, 3, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 3, 0, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negation, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [228] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_while(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
